sudo: required

services:
  - docker

before_install:
  - docker build -t uudashr/fibgo .
  - docker run -d --name fibgo-server -p 127.0.0.1:8080:8080 uudashr/fibgo
  - docker ps -a

script:
  - curl --fail http://127.0.0.1:8080/numbers || exit 1

after_script:
  - docker stop fibgo-server
  - docker rm -v fibgo-server
