sudo: false

language: node_js

node_js:
  - "6"

cache:
  yarn: true
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=kurio-dev
    - CLUSTER_NAME_STG=fibgo-cluster-stg
    - CLUSTER_NAME_PRD=fibgo-cluster
    - COMPUTE_ZONE=asia-east1-c
    - DOCKER_IMAGE_NAME_STG=fibgo-stg
    - DOCKER_IMAGE_NAME_PRD=fibgo
    - KUBE_DEPLOYMENT_NAME=fibgo-deployment
    - KUBE_DEPLOYMENT_CONTAINER_NAME=fibgo
    - NODE_EV=CI

install:
  - yarn install

script:
  - docker build -t fibgo .
  - docker run -d --name fibgo-server -p 127.0.0.1:8080:8080 fibgo
  - curl --fail http://127.0.0.1:8080/numbers || exit 1

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
      curl https://sdk.cloud.google.com | bash;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: .travis/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: .travis/deploy-production.sh
    skip_cleanup: true
    on:
      branch: master

after_script:
  - docker stop fibgo-server
  - docker rm -v fibgo-server
